#!/usr/bin/env python
"""
Calculate acceptance change when shifting the leading lepton threshold from 25 to 27 GeV.

Usage:
    python calculate_acceptance.py <output_file.root>

This script reads the acceptance histograms generated by AIZ.C with the asymmetric
fiducial cut option enabled and calculates:
1. Acceptance ratio (fraction of events retained)
2. Acceptance loss percentage  
3. Differential acceptance as a function of pT
"""

import sys
import ROOT

def calculate_acceptance(root_file):
    """
    Calculate acceptance when moving from 25 GeV to 27 GeV leading threshold.
    
    Args:
        root_file (str): Path to ROOT file output from AIZ.C
    """
    
    try:
        f = ROOT.TFile.Open(root_file, "READ")
        if not f or f.IsZombie():
            print(f"ERROR: Unable to open file {root_file}")
            return
        
        # Try to get the acceptance histograms
        hLeadPt = f.Get("acceptance_leadingPt")
        hSubleadPt = f.Get("acceptance_subleadingPt")
        hLeadVsSubleadPt = f.Get("acceptance_leadingPt_vs_subleadingPt")
        
        if not hLeadPt:
            print(f"ERROR: Cannot find 'acceptance_leadingPt' histogram in {root_file}")
            print("Make sure AIZ.C was run with FiducialCutCCAsym = true")
            return
        
        print("\n" + "="*70)
        print("ACCEPTANCE CALCULATION: Leading pT threshold 25 GeV → 27 GeV")
        print("(Subleading threshold fixed at 25 GeV, both leptons |η| ≤ 2.5)")
        print("="*70)
        
        # Count events above different thresholds for the leading pT
        total_weighted = hLeadPt.Integral()
        above_25_leading = hLeadPt.Integral(hLeadPt.FindBin(25.0), -1)
        above_27_leading = hLeadPt.Integral(hLeadPt.FindBin(27.0), -1)
        
        print(f"\nLeading pT Distribution Statistics:")
        print(f"  Total weighted events:           {total_weighted:.2f}")
        print(f"  Events with p_T(lead) ≥ 25 GeV: {above_25_leading:.2f}")
        print(f"  Events with p_T(lead) ≥ 27 GeV: {above_27_leading:.2f}")
        
        # Basic acceptance calculation (assumes subleading is already > 25 GeV in the histogram)
        if above_25_leading > 0:
            acceptance = above_27_leading / above_25_leading
            acceptance_loss = (1.0 - acceptance) * 100.0
            
            print(f"\nSimple Acceptance (leading pT only):")
            print(f"  Acceptance ratio:   {acceptance:.6f}")
            print(f"  Acceptance loss:    {acceptance_loss:.2f}%")
        
        # More detailed analysis using 2D histogram if available
        if hLeadVsSubleadPt:
            print(f"\n2D Analysis (p_T(leading) vs p_T(subleading)):")
            
            # Count events in different regions
            total_2d = hLeadVsSubleadPt.Integral()
            
            # Region: both above original thresholds (25, 25)
            y_bin_25 = hLeadVsSubleadPt.GetYaxis().FindBin(25.0)
            x_bin_25 = hLeadVsSubleadPt.GetXaxis().FindBin(25.0)
            x_bin_27 = hLeadVsSubleadPt.GetXaxis().FindBin(27.0)
            
            events_25_25 = hLeadVsSubleadPt.Integral(x_bin_25, -1, y_bin_25, -1)
            events_27_25 = hLeadVsSubleadPt.Integral(x_bin_27, -1, y_bin_25, -1)
            
            print(f"  Events with p_T(lead)≥25 and p_T(sublead)≥25 GeV: {events_25_25:.2f}")
            print(f"  Events with p_T(lead)≥27 and p_T(sublead)≥25 GeV: {events_27_25:.2f}")
            
            if events_25_25 > 0:
                acceptance_2d = events_27_25 / events_25_25
                acceptance_loss_2d = (1.0 - acceptance_2d) * 100.0
                
                print(f"\n  Acceptance ratio:   {acceptance_2d:.6f}")
                print(f"  Acceptance loss:    {acceptance_loss_2d:.2f}%")
        
        # Print differential acceptance in bins
        print(f"\nDifferential Analysis (by leading pT bin):")
        print(f"  {'Bin Range (GeV)':<20} {'Events p_T≥25':<20} {'Events p_T≥27':<20} {'Efficiency':<15}")
        print(f"  {'-'*70}")
        
        nbins = hLeadPt.GetNbinsX()
        for i in range(1, min(nbins + 1, 20)):  # Show first 20 bins
            bin_low = hLeadPt.GetBinLowEdge(i)
            bin_high = hLeadPt.GetBinLowEdge(i) + hLeadPt.GetBinWidth(i)
            
            if bin_low >= 25.0:
                integral_25 = hLeadPt.Integral(hLeadPt.FindBin(25.0), i)
                integral_27 = hLeadPt.Integral(hLeadPt.FindBin(27.0), i)
                
                if integral_25 > 0:
                    eff = integral_27 / integral_25
                    print(f"  [{bin_low:5.1f}, {bin_high:5.1f}]{' '*5} {integral_25:15.2f}  {integral_27:15.2f}  {eff:14.4f}")
        
        print("\n" + "="*70)
        print("INTERPRETATION:")
        print("  - Acceptance loss represents % of events rejected by 27 GeV cut")
        print("  - Use this to quantify impact on statistical precision")
        print("  - Efficiency varies with pT due to event kinematics")
        print("="*70 + "\n")
        
        f.Close()
        
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python calculate_acceptance.py <output_file.root>")
        print("\nExample: python calculate_acceptance.py AIZ_CC_Asym_Zai.root")
        sys.exit(1)
    
    root_file = sys.argv[1]
    calculate_acceptance(root_file)
