#!/usr/bin/env python
"""
Calculate and visualize acceptance change based on fiducial cuts applied in AIZ.C.

Usage (Single file mode):
    python calculate_acceptance.py <output_file.root>

Usage (Two-file comparison mode):
    python calculate_acceptance.py <file_with_cut.root> <file_without_cut.root>

Single file mode:
This script reads the acceptance and efficiency histograms generated by AIZ.C and calculates:
1. Acceptance ratio (fraction of events retained)
2. Acceptance loss percentage  
3. Differential acceptance as a function of kinematic variables
4. Creates plots showing before/after distributions and efficiency

Usage (Multi-file comparison mode):
    python calculate_acceptance.py <reference.root> <file2.root> <file3.root> [...]

Multi-file comparison mode:
Overlays three or more files and shows each file divided by the first (reference) file.

Two-file comparison mode:
Compares two ROOT files to compute acceptance differences and efficiency ratios.
Generates overlaid plots with ratio analysis for each kinematic variable.
Useful for comparing impact of different fiducial cuts on the same sample.

Automatically detects which fiducial cut was applied (CC, EtaOnly, or CCAsym) and analyzes accordingly.

Generates output plots:
Single file mode:
- acceptance_summary.pdf: Summary plots of cos(theta), pT distributions
- acceptance_efficiency.pdf: Efficiency curves for key variables
- acceptance_2d_analysis.pdf: 2D kinematic correlations

Two-file comparison mode:
- acceptance_overlay_comparison.pdf: Overlaid histograms with ratio plots
- acceptance_ratio_analysis.pdf: Detailed ratio and relative difference analysis

Multi-file comparison mode:
- acceptance_overlay_comparison_multi_<labels>.pdf: Normalized overlays, ratios to first file
- acceptance_overlay_comparison_unnormalized_multi_<labels>.pdf: Same, unnormalized
- acceptance_A4_sensitivity_loss_comparison_multi_<labels>.pdf: A4 loss factor overlay and ratios
"""

import sys
import ROOT
import math

# Set ROOT to batch mode to avoid GUI popups
ROOT.gROOT.SetBatch(True)

def detect_efficiency_suffix(root_file):
    """
    Detect which fiducial cut mode was used by checking for histogram suffixes.
    
    Args:
        root_file (str): Path to ROOT file
        
    Returns:
        str: Suffix string (_CC, _EtaOnly, _CCAsym, or _CCconf<pT>), or None if not found
    """
    try:
        f = ROOT.TFile.Open(root_file, "READ")
        if not f or f.IsZombie():
            return None
        
        # Try suffixes in priority order: check _CCconf first (more specific),
        # then other explicit patterns, then default _CC
        import re
        
        # Check for _CCconf<number> pattern (e.g., _CCconf27)
        keys = f.GetListOfKeys()
        for key in keys:
            key_name = key.GetName()
            match = re.search(r'_CCconf\d+', key_name)
            if match:
                suffix = match.group(0)
                test_hist = f.Get(f"eff_costheta_before{suffix}")
                if test_hist:
                    f.Close()
                    return suffix
        
        # Try other explicit suffixes
        for suffix in ["_CCAsym", "_EtaOnly", "_CC"]:
            test_hist = f.Get(f"eff_costheta_before{suffix}")
            if test_hist:
                f.Close()
                return suffix
        
        f.Close()
        return None
        
    except Exception as e:
        print(f"ERROR detecting suffix: {e}")
        return None

def derive_cut_label(root_file):
    """Derive a short cut-mode label from the AIZ.C output file name tag.

    AIZ.C encodes the active fiducial cut directly in the output file name,
    e.g. ..._Fiducial_CCAsym_..., ..._Fiducial_EtaOnly_...,
    ..._Fiducial_CCCF_..., ..._Fiducial_CFonly_..., or plain ..._Fiducial_...
    for the default symmetric CC cut. Files without "_Fiducial_" at all were
    produced with FiducialCut=false (no cut applied, full phase space).

    Args:
        root_file (str): Path to ROOT file (only the base name is inspected)

    Returns:
        str: Short label such as "CC", "CCAsym", "EtaOnly", "CCCF", "CFonly",
             or "NoCut".
    """
    import os
    import re
    name = os.path.basename(root_file)
    if "_EtaOnly_" in name:
        return "EtaOnly"
    if "_CCCF_" in name:
        return "CCCF"
    if "_CFonly_" in name:
        return "CFonly"
    if "_CCAsym_" in name:
        return "CCAsym"
    # Check for CCconf pattern with regex
    match = re.search(r'_CCconf(\d+)_', name)
    if match:
        pt = match.group(1)
        return f"CCconf{pt}"
    if "_Fiducial_" in name:
        return "CC"
    return "NoCut"

def setup_histogram_style(hist, color=1, marker_style=20):
    """Setup histogram style for plotting."""
    hist.SetLineColor(color)
    hist.SetMarkerColor(color)
    hist.SetMarkerStyle(marker_style)
    hist.SetLineWidth(2)
    hist.SetStats(False)

def get_suffix_label(suffix):
    """
    Convert an efficiency suffix to a human-readable label.
    
    Args:
        suffix (str): Suffix such as "_CC", "_EtaOnly", "_CCAsym", or "_CCconf27"
        
    Returns:
        str: Human-readable label
    """
    import re
    static_labels = {
        "_CC": "symmetric CC",
        "_EtaOnly": "eta-only",
        "_CCAsym": "asymmetric CC"
    }
    
    if suffix in static_labels:
        return static_labels[suffix]
    
    # Handle dynamic _CCconf pattern
    match = re.match(r'_CCconf(\d+)', suffix)
    if match:
        pt = match.group(1)
        return f"CC (pT > {pt} GeV)"
    
    return suffix

def normalize_histogram(hist):
    """Normalize histogram to unit area."""
    integral = hist.Integral()
    if integral > 0:
        hist.Scale(1.0 / integral)
    return hist

def calculate_efficiency_histogram(h_after, h_before):
    """
    Calculate efficiency histogram as (after / before).
    
    Args:
        h_after: Histogram after cut
        h_before: Histogram before cut
        
    Returns:
        TH1F efficiency histogram
    """
    h_eff = h_after.Clone("eff_temp")
    h_eff.Divide(h_before)
    return h_eff

def calculate_ratio_histogram(h_num, h_denom):
    """
    Calculate ratio histogram as (numerator / denominator).
    Handles zero bins safely.
    
    Args:
        h_num: Numerator histogram
        h_denom: Denominator histogram
        
    Returns:
        TH1F ratio histogram
    """
    h_ratio = h_num.Clone("ratio_temp")
    h_ratio.Divide(h_denom)
    return h_ratio

def set_ratio_axis_range(h_ratio, h_denom):
    """Set the ratio axis from the central 95% of valid bin values, ignoring errors."""
    values = [
        float(h_ratio.GetBinContent(i))
        for i in range(1, h_ratio.GetNbinsX() + 1)
        if h_denom.GetBinContent(i) != 0
        and math.isfinite(float(h_ratio.GetBinContent(i)))
    ]
    if not values:
        print("WARNING: Cannot set ratio axis range; no valid ratio bins")
        return

    values.sort()

    def percentile(fraction):
        position = (len(values) - 1) * fraction
        lower = int(position)
        upper = min(lower + 1, len(values) - 1)
        weight = position - lower
        return values[lower] * (1.0 - weight) + values[upper] * weight

    lower = percentile(0.025)
    upper = percentile(0.975)
    padding = (upper - lower) * 0.1
    if padding == 0:
        padding = max(abs(lower) * 0.05, 0.05)

    h_ratio.SetMinimum(lower - padding)
    h_ratio.SetMaximum(upper + padding)

def calculate_relative_difference(h1, h2):
    """
    Calculate relative difference histogram as (h1 - h2) / h2.
    
    Args:
        h1: First histogram
        h2: Second histogram (reference)
        
    Returns:
        TH1F relative difference histogram
    """
    h_diff = h1.Clone("rel_diff_temp")
    h_diff.Add(h2, -1.0)  # h_diff = h1 - h2
    
    # Divide by h2 element-wise
    for i in range(1, h_diff.GetNbinsX() + 1):
        h2_val = h2.GetBinContent(i)
        if h2_val != 0:
            diff_val = h_diff.GetBinContent(i)
            h_diff.SetBinContent(i, diff_val / h2_val)
        else:
            h_diff.SetBinContent(i, 0)
    
    return h_diff

def create_overlay_comparison_plots(root_file1, root_file2, eff_suffix1, eff_suffix2,
                                     label1="File 1", label2="File 2"):
    """Create overlaid comparison plots from two files with ratio.
    
    Args:
        root_file1 (str): Path to first ROOT file (typically with cut)
        root_file2 (str): Path to second ROOT file (typically without cut)
        eff_suffix1 (str): Efficiency histogram suffix for file 1
        eff_suffix2 (str): Efficiency histogram suffix for file 2
        label1 (str): Short cut-mode label for file 1 (e.g. "CC")
        label2 (str): Short cut-mode label for file 2 (e.g. "CCAsym")
    """
    try:
        f1 = ROOT.TFile.Open(root_file1, "READ")
        f2 = ROOT.TFile.Open(root_file2, "READ")
        
        if not f1 or f1.IsZombie() or not f2 or f2.IsZombie():
            print(f"ERROR: Unable to open one or both files")
            return
        
        # Create canvas with 2 columns: overlay and ratio
        canvas = ROOT.TCanvas("c_overlay", "File Comparison: Overlay with Ratio", 1600, 1680)
        canvas.Divide(2, 6)
        unnormalized_canvas = ROOT.TCanvas(
            "c_overlay_unnormalized", "Unnormalized File Comparison: Overlay with Ratio", 1600, 1680
        )
        unnormalized_canvas.Divide(2, 6)
        
        # Define histogram pairs to compare
        comparisons = [
            (f"eff_costheta_after{eff_suffix1}", f"eff_costheta_after{eff_suffix2}", "cos#theta_{CS}", 1, 2),
            (f"eff_leadingPt_after{eff_suffix1}", f"eff_leadingPt_after{eff_suffix2}", "p_{T}(leading l) [GeV]", 3, 4),
            (f"eff_subleadingPt_after{eff_suffix1}", f"eff_subleadingPt_after{eff_suffix2}", "p_{T}(subleading l) [GeV]", 5, 6),
            (f"eff_deltaEta_after{eff_suffix1}", f"eff_deltaEta_after{eff_suffix2}", "|#Delta#eta(ll)|", 7, 8),
            (f"eff_pT_Z_after{eff_suffix1}", f"eff_pT_Z_after{eff_suffix2}", "p_{T}(Z) [GeV]", 9, 10),
            (f"eff_Y_ll_after{eff_suffix1}", f"eff_Y_ll_after{eff_suffix2}", "|y(Z)|", 11, 12),
        ]
        ratio_zoom_ranges = {
            "p_{T}(subleading l) [GeV]": (None, None, 0.9, 1.7),
            "|#Delta#eta(ll)|": (0.0, 2.2, 0.9, 2.6),
        }
        unnormalized_ratio_zoom_y_ranges = {
            "p_{T}(subleading l) [GeV]": (0.9, 1.7),
            "|#Delta#eta(ll)|": (0.9, 2.8),
        }
        
        print("\n" + "="*70)
        print("CREATING OVERLAY COMPARISON PLOTS")
        print("="*70)
        
        for h1_name, h2_name, var_label, pad_overlay, pad_ratio in comparisons:
            h1 = f1.Get(h1_name)
            h2 = f2.Get(h2_name)
            
            if not h1 or not h2:
                print(f"WARNING: Could not find {h1_name} or {h2_name}")
                continue
            
            # Normalize for comparison
            h1_norm = h1.Clone(f"{h1_name}_norm")
            h2_norm = h2.Clone(f"{h2_name}_norm")
            normalize_histogram(h1_norm)
            normalize_histogram(h2_norm)
            
            # Left pad: overlay
            canvas.cd(pad_overlay)
            ROOT.gPad.SetLogy(0)
            
            setup_histogram_style(h1_norm, ROOT.kBlue + 1, 20)
            setup_histogram_style(h2_norm, ROOT.kRed + 1, 22)
            
            h1_norm.Draw("PE")
            h2_norm.Draw("PE SAME")
            
            legend = ROOT.TLegend(0.60, 0.75, 0.95, 0.95)
            legend.AddEntry(h1_norm, f"File 1 ({label1})", "PE")
            legend.AddEntry(h2_norm, f"File 2 ({label2})", "PE")
            legend.Draw()
            
            h1_norm.SetTitle(f"Normalized {var_label} - Overlay")
            h1_norm.GetXaxis().SetTitle(var_label)
            h1_norm.GetYaxis().SetTitle("Normalized entries")
            
            # Right pad: ratio of the normalized histograms shown on the left
            canvas.cd(pad_ratio)
            ROOT.gPad.SetGrid(1, 1)
            
            h_ratio = calculate_ratio_histogram(h1_norm, h2_norm)
            setup_histogram_style(h_ratio, ROOT.kGreen + 2, 20)
            zoom_range = ratio_zoom_ranges.get(var_label)
            zoom_suffix = " (zoomed)" if zoom_range else ""
            h_ratio.SetTitle(f"Normalized ratio ({label1}/{label2}) - {var_label}{zoom_suffix}")
            h_ratio.GetXaxis().SetTitle(var_label)
            h_ratio.GetYaxis().SetTitle(f"Normalized ratio ({label1}/{label2})")
            set_ratio_axis_range(h_ratio, h2)
            if zoom_range:
                x_min, x_max, y_min, y_max = zoom_range
                if x_min is not None:
                    h_ratio.GetXaxis().SetRangeUser(x_min, x_max)
                h_ratio.SetMinimum(y_min)
                h_ratio.SetMaximum(y_max)
            h_ratio.Draw("PE")
            
            # Add line at 1.0
            line = ROOT.TLine(h_ratio.GetXaxis().GetXmin(), 1.0,
                            h_ratio.GetXaxis().GetXmax(), 1.0)
            line.SetLineStyle(2)
            line.SetLineColor(ROOT.kBlack)
            line.Draw()
            
            # Second canvas: compare the original, unnormalized histograms
            unnormalized_canvas.cd(pad_overlay)
            ROOT.gPad.SetLogy(0)

            setup_histogram_style(h1, ROOT.kBlue + 1, 20)
            setup_histogram_style(h2, ROOT.kRed + 1, 22)
            h1.Draw("PE")
            h2.Draw("PE SAME")

            raw_legend = ROOT.TLegend(0.60, 0.75, 0.95, 0.95)
            raw_legend.AddEntry(h1, f"File 1 ({label1})", "PE")
            raw_legend.AddEntry(h2, f"File 2 ({label2})", "PE")
            raw_legend.Draw()

            h1.SetTitle(f"Unnormalized {var_label} - Overlay")
            h1.GetXaxis().SetTitle(var_label)
            h1.GetYaxis().SetTitle("Entries")

            unnormalized_canvas.cd(pad_ratio)
            ROOT.gPad.SetGrid(1, 1)

            raw_ratio = calculate_ratio_histogram(h1, h2)
            setup_histogram_style(raw_ratio, ROOT.kGreen + 2, 20)
            raw_ratio.SetTitle(f"Unnormalized ratio ({label1}/{label2}) - {var_label}{zoom_suffix}")
            raw_ratio.GetXaxis().SetTitle(var_label)
            raw_ratio.GetYaxis().SetTitle(f"Unnormalized ratio ({label1}/{label2})")
            set_ratio_axis_range(raw_ratio, h2)
            if zoom_range:
                if x_min is not None:
                    raw_ratio.GetXaxis().SetRangeUser(x_min, x_max)
                y_min, y_max = unnormalized_ratio_zoom_y_ranges[var_label]
                raw_ratio.SetMinimum(y_min)
                raw_ratio.SetMaximum(y_max)
            raw_ratio.Draw("PE")

            raw_line = ROOT.TLine(raw_ratio.GetXaxis().GetXmin(), 1.0,
                                  raw_ratio.GetXaxis().GetXmax(), 1.0)
            raw_line.SetLineStyle(2)
            raw_line.SetLineColor(ROOT.kBlack)
            raw_line.Draw()

            print(f"Created overlay comparison plot for {var_label}")
        
        output_name = f"acceptance_overlay_comparison_{label1}_vs_{label2}.pdf"
        canvas.SaveAs(output_name)
        print(f"\nSaved overlay comparison plots to: {output_name}\n")
        unnormalized_output_name = (
            f"acceptance_overlay_comparison_unnormalized_{label1}_vs_{label2}.pdf"
        )
        unnormalized_canvas.SaveAs(unnormalized_output_name)
        print(f"Saved unnormalized overlay comparison plots to: {unnormalized_output_name}\n")
        
        f1.Close()
        f2.Close()
        
    except Exception as e:
        print(f"ERROR in create_overlay_comparison_plots: {e}")
        import traceback
        traceback.print_exc()

def create_ratio_analysis_plots(root_file1, root_file2, eff_suffix1, eff_suffix2,
                                 label1="File 1", label2="File 2"):
    """Create detailed ratio analysis plots.
    
    Args:
        root_file1 (str): Path to first ROOT file
        root_file2 (str): Path to second ROOT file
        eff_suffix1 (str): Efficiency histogram suffix for file 1
        eff_suffix2 (str): Efficiency histogram suffix for file 2
        label1 (str): Short cut-mode label for file 1 (e.g. "CC")
        label2 (str): Short cut-mode label for file 2 (e.g. "CCAsym")
    """
    try:
        f1 = ROOT.TFile.Open(root_file1, "READ")
        f2 = ROOT.TFile.Open(root_file2, "READ")
        
        if not f1 or f1.IsZombie() or not f2 or f2.IsZombie():
            print(f"ERROR: Unable to open one or both files")
            return
        
        # Create canvas with ratio plots side by side
        canvas = ROOT.TCanvas("c_ratio_analysis", "Ratio Analysis", 1600, 500)
        canvas.Divide(3, 1)
        
        # Define histogram pairs to analyze
        analyses = [
            (f"eff_costheta_after{eff_suffix1}", f"eff_costheta_after{eff_suffix2}", "cos#theta_{CS}", 1),
            (f"eff_leadingPt_after{eff_suffix1}", f"eff_leadingPt_after{eff_suffix2}", "p_{T}(leading l) [GeV]", 2),
            (f"eff_deltaEta_after{eff_suffix1}", f"eff_deltaEta_after{eff_suffix2}", "|#Delta#eta(ll)|", 3),
        ]
        
        print("\n" + "="*70)
        print("CREATING RATIO ANALYSIS PLOTS")
        print("="*70)
        
        for h1_name, h2_name, var_label, pad_num in analyses:
            h1 = f1.Get(h1_name)
            h2 = f2.Get(h2_name)
            
            if not h1 or not h2:
                print(f"WARNING: Could not find {h1_name} or {h2_name}")
                continue
            
            # Ratio histogram
            canvas.cd(pad_num)
            ROOT.gPad.SetGrid(1, 1)
            
            h_ratio = calculate_ratio_histogram(h1, h2)
            setup_histogram_style(h_ratio, ROOT.kBlue + 1, 20)
            h_ratio.SetTitle(f"Ratio ({label1}/{label2}) - {var_label}")
            h_ratio.GetXaxis().SetTitle(var_label)
            h_ratio.GetYaxis().SetTitle(f"Ratio ({label1}/{label2})")
            h_ratio.Draw("PE")
            
            line = ROOT.TLine(h_ratio.GetXaxis().GetXmin(), 1.0,
                             h_ratio.GetXaxis().GetXmax(), 1.0)
            line.SetLineStyle(2)
            line.SetLineColor(ROOT.kBlack)
            line.Draw()
            
            # Calculate statistics
            ratio_mean = h_ratio.GetMean()
            
            print(f"\n{var_label}:")
            print(f"  Mean ratio ({label1}/{label2}): {ratio_mean:.6f}")
        
        output_name = f"acceptance_ratio_analysis_{label1}_vs_{label2}.pdf"
        canvas.SaveAs(output_name)
        print(f"\nSaved ratio analysis plots to: {output_name}\n")
        
        f1.Close()
        f2.Close()
        
    except Exception as e:
        print(f"ERROR in create_ratio_analysis_plots: {e}")
        import traceback
        traceback.print_exc()

def create_sensitivity_loss_comparison_plots(root_file1, root_file2,
                                              label1="File 1", label2="File 2"):
    """Compare the A4 SensitivityLossFactor between two files.

    A4_SensitivityLossFactor (and its underlying A4_sumW_*/A4_P4sqNum_* inputs)
    are written by AIZ.C without an effSuffix, since they quantify how much the
    active fiducial cut in *that* file inflates the statistical uncertainty on
    A4 relative to the uncut sample within the same file. This function does
    not repeat that before/after calculation; it compares the already-computed
    per-file SensitivityLossFactor histograms against each other, file-to-file.

    Args:
        root_file1 (str): Path to first ROOT file
        root_file2 (str): Path to second ROOT file
        label1 (str): Short cut-mode label for file 1 (e.g. "CC")
        label2 (str): Short cut-mode label for file 2 (e.g. "CCAsym")
    """
    try:
        f1 = ROOT.TFile.Open(root_file1, "READ")
        f2 = ROOT.TFile.Open(root_file2, "READ")
        
        if not f1 or f1.IsZombie() or not f2 or f2.IsZombie():
            print(f"ERROR: Unable to open one or both files")
            return
        
        h1 = f1.Get("A4_SensitivityLossFactor")
        h2 = f2.Get("A4_SensitivityLossFactor")
        
        if not h1 or not h2:
            print(f"WARNING: A4_SensitivityLossFactor not found in one or both files; "
                  f"skipping sensitivity-loss comparison "
                  f"(re-run AIZ.C to produce it if missing)")
            f1.Close()
            f2.Close()
            return
        
        print("\n" + "="*70)
        print("A4 SENSITIVITY LOSS FACTOR COMPARISON")
        print("="*70)
        
        canvas = ROOT.TCanvas("c_A4_sensitivity_loss_comparison",
                               "A4 Sensitivity Loss Factor: File Comparison", 1600, 700)
        canvas.Divide(2, 1)
        
        h1_clone = h1.Clone("A4_SensitivityLossFactor_file1")
        h2_clone = h2.Clone("A4_SensitivityLossFactor_file2")
        # A4_SensitivityLossFactor is stored without Sumw2, so ROOT would draw
        # sqrt(content) as a meaningless error bar; show markers only.
        for hist in (h1_clone, h2_clone):
            for b in range(1, hist.GetNbinsX() + 1):
                hist.SetBinError(b, 0.0)
        
        # Left pad: overlay of both files' loss factors (log y: the last |y| bin
        # is ~50x larger than the bulk)
        canvas.cd(1)
        ROOT.gPad.SetGrid(1, 1)
        ROOT.gPad.SetLogy(1)
        
        setup_histogram_style(h1_clone, ROOT.kBlue + 1, 20)
        setup_histogram_style(h2_clone, ROOT.kRed + 1, 22)
        
        h1_clone.SetTitle("A_{4} Sensitivity Loss Factor - Overlay")
        h1_clone.GetYaxis().SetTitle("#sigma(A_{4})_{after}/#sigma(A_{4})_{before}")
        h1_clone.SetMinimum(0.5)
        h1_clone.Draw("P")
        h2_clone.Draw("P SAME")
        
        legend = ROOT.TLegend(0.60, 0.75, 0.92, 0.88)
        legend.AddEntry(h1_clone, f"File 1 ({label1})", "P")
        legend.AddEntry(h2_clone, f"File 2 ({label2})", "P")
        legend.Draw()
        
        line_unity = ROOT.TLine(h1_clone.GetXaxis().GetXmin(), 1.0,
                                 h1_clone.GetXaxis().GetXmax(), 1.0)
        line_unity.SetLineStyle(2)
        line_unity.SetLineColor(ROOT.kBlack)
        line_unity.Draw()
        
        # Right pad: ratio of the two files' loss factors (File1 / File2). Both
        # files share the same uncut "before" sample, so this isolates the
        # effect of the two cuts: ratio > 1 means File 1's cut costs more
        # A4 sensitivity.
        canvas.cd(2)
        ROOT.gPad.SetGrid(1, 1)
        
        h_ratio = h1_clone.Clone("A4_SensitivityLossFactor_ratio")
        h_ratio.Reset()
        ratio_values = []
        for b in range(1, h1.GetNbinsX() + 1):
            v1, v2 = h1.GetBinContent(b), h2.GetBinContent(b)
            if v1 != 0 and v2 != 0:
                h_ratio.SetBinContent(b, v1 / v2)
                h_ratio.SetBinError(b, 0.0)
                ratio_values.append(v1 / v2)
        setup_histogram_style(h_ratio, ROOT.kGreen + 2, 20)
        h_ratio.SetTitle(f"Ratio ({label1} / {label2}) - A_{{4}} Sensitivity Loss Factor")
        h_ratio.GetYaxis().SetTitle(f"Loss factor ratio ({label1} / {label2})")
        if ratio_values:
            y_min = min(1.0, min(ratio_values))
            y_max = max(1.0, max(ratio_values))
            padding = max((y_max - y_min) * 0.1, 0.01)
            h_ratio.SetMinimum(y_min - padding)
            h_ratio.SetMaximum(y_max + padding)
        h_ratio.Draw("P")
        
        line_ratio_unity = ROOT.TLine(h_ratio.GetXaxis().GetXmin(), 1.0,
                                      h_ratio.GetXaxis().GetXmax(), 1.0)
        line_ratio_unity.SetLineStyle(2)
        line_ratio_unity.SetLineColor(ROOT.kBlack)
        line_ratio_unity.Draw()
        
        output_name = f"acceptance_A4_sensitivity_loss_comparison_{label1}_vs_{label2}.pdf"
        canvas.SaveAs(output_name)
        print(f"\nSaved A4 sensitivity-loss comparison to: {output_name}")
        
        # Per-bin printout
        print(f"\n{'BinLow':>10} {'BinHigh':>10} {'LossFactor1':>14} {'LossFactor2':>14} {'Difference(1-2)':>16}")
        for b in range(1, h1.GetNbinsX() + 1):
            lo = h1.GetXaxis().GetBinLowEdge(b)
            hi = h1.GetXaxis().GetBinUpEdge(b)
            val1 = h1.GetBinContent(b)
            val2 = h2.GetBinContent(b)
            difference = val1 - val2
            print(f"{lo:10.2f} {hi:10.2f} {val1:14.4f} {val2:14.4f} {difference:16.4f}")
        
        # Inclusive headline number: unweighted arithmetic mean of valid
        # (nonzero) bin LossFactor values. Note: TH1::GetMean() would instead
        # return the x-axis-weighted mean, which is not what we want here.
        def mean_of_valid_bins(hist):
            values = [hist.GetBinContent(b) for b in range(1, hist.GetNbinsX() + 1)
                      if hist.GetBinContent(b) != 0]
            return (sum(values) / len(values)) if values else float("nan")
        
        mean1 = mean_of_valid_bins(h1)
        mean2 = mean_of_valid_bins(h2)
        common_valid_differences = [
            h1.GetBinContent(b) - h2.GetBinContent(b)
            for b in range(1, h1.GetNbinsX() + 1)
            if h1.GetBinContent(b) != 0 and h2.GetBinContent(b) != 0
        ]
        mean_difference = (
            sum(common_valid_differences) / len(common_valid_differences)
            if common_valid_differences else float("nan")
        )
        print(f"\nMean LossFactor (bin-averaged): File 1 ({label1}) = {mean1:.4f}, "
              f"File 2 ({label2}) = {mean2:.4f}")
        print(f"Mean Difference ({label1} - {label2}, common valid bins): {mean_difference:.4f}")
        
        f1.Close()
        f2.Close()
        
    except Exception as e:
        print(f"ERROR in create_sensitivity_loss_comparison_plots: {e}")
        import traceback
        traceback.print_exc()

def compare_two_files(root_file1, root_file2):
    """
    Compare acceptance between two ROOT files.
    
    Args:
        root_file1 (str): Path to ROOT file 1 (typically with cut)
        root_file2 (str): Path to ROOT file 2 (typically without cut)
    """
    try:
        # Detect efficiency suffixes for both files
        eff_suffix1 = detect_efficiency_suffix(root_file1)
        eff_suffix2 = detect_efficiency_suffix(root_file2)
        
        if not eff_suffix1 or not eff_suffix2:
            print(f"ERROR: Could not detect efficiency histograms in one or both files")
            return
        
        # Short cut-mode labels derived from the output file name itself (per
        # AIZ.C's "prefix" naming convention), used for legends and plot file
        # names. This covers all 5 fiducial-cut modes, unlike eff_suffix1/2
        # above which cannot distinguish CFonly/CCCF from the default CC cut.
        label1 = derive_cut_label(root_file1)
        label2 = derive_cut_label(root_file2)
        
        print(f"\n" + "="*70)
        print("TWO-FILE COMPARISON MODE")
        print("="*70)
        print(f"File 1: {root_file1}")
        print(f"  Detected cut mode (histogram suffix): {get_suffix_label(eff_suffix1)}")
        print(f"  Cut-mode label (from file name): {label1}")
        print(f"File 2: {root_file2}")
        print(f"  Detected cut mode (histogram suffix): {get_suffix_label(eff_suffix2)}")
        print(f"  Cut-mode label (from file name): {label2}")
        print("="*70)
        
        f1 = ROOT.TFile.Open(root_file1, "READ")
        f2 = ROOT.TFile.Open(root_file2, "READ")
        
        if not f1 or f1.IsZombie() or not f2 or f2.IsZombie():
            print(f"ERROR: Unable to open one or both files")
            return
        
        # Get leading pT histograms for basic comparison
        hLeadPt1 = f1.Get("acceptance_leadingPt")
        hLeadPt2 = f2.Get("acceptance_leadingPt")
        
        if hLeadPt1 and hLeadPt2:
            print(f"\n" + "="*70)
            print("LEADING PT ACCEPTANCE COMPARISON")
            print("="*70)
            
            total1 = hLeadPt1.Integral()
            total2 = hLeadPt2.Integral()
            
            above_25_1 = hLeadPt1.Integral(hLeadPt1.FindBin(25.0), -1)
            above_25_2 = hLeadPt2.Integral(hLeadPt2.FindBin(25.0), -1)
            
            above_27_1 = hLeadPt1.Integral(hLeadPt1.FindBin(27.0), -1)
            above_27_2 = hLeadPt2.Integral(hLeadPt2.FindBin(27.0), -1)
            
            print(f"\nFile 1 Statistics:")
            print(f"  Events with p_T(lead) ≥ 25 GeV: {above_25_1:.2f}")
            print(f"  Events with p_T(lead) ≥ 27 GeV: {above_27_1:.2f}")
            
            print(f"\nFile 2 Statistics:")
            print(f"  Events with p_T(lead) ≥ 25 GeV: {above_25_2:.2f}")
            print(f"  Events with p_T(lead) ≥ 27 GeV: {above_27_2:.2f}")
            
            if above_25_1 > 0 and above_25_2 > 0:
                eff1 = above_27_1 / above_25_1
                eff2 = above_27_2 / above_25_2
                
                print(f"\nWithin-File Acceptance (p_T ≥ 27 GeV relative to p_T ≥ 25 GeV, same file):")
                print(f"  File 1 acceptance: {eff1:.6f}")
                print(f"  File 2 acceptance: {eff2:.6f}")
                print(f"  Ratio of within-file acceptances (File1/File2): {eff1/eff2:.6f}")
                print(f"  Relative difference: {((eff1-eff2)/eff2)*100:.2f}%")
            
            if total1 > 0 and total2 > 0:
                print(f"\nCross-File Total Event Comparison (p_T(lead) ≥ 25 GeV):")
                print(f"  File 1 total events: {above_25_1:.2f}")
                print(f"  File 2 total events: {above_25_2:.2f}")
                print(f"  Ratio (File1/File2): {above_25_1/above_25_2:.6f}")
                print(f"  Relative difference: {((above_25_1-above_25_2)/above_25_2)*100:.2f}%")
        
        # Get cos(theta) histograms
        h_costh1_after = f1.Get(f"eff_costheta_after{eff_suffix1}")
        h_costh2_after = f2.Get(f"eff_costheta_after{eff_suffix2}")
        
        if h_costh1_after and h_costh2_after:
            print(f"\n" + "="*70)
            print("COS(THETA) EFFICIENCY COMPARISON")
            print("="*70)
            
            total_costh1 = h_costh1_after.Integral()
            total_costh2 = h_costh2_after.Integral()
            
            print(f"\nCross-File Total Event Comparison (after cut):")
            print(f"  File 1 total events: {total_costh1:.2f}")
            print(f"  File 2 total events: {total_costh2:.2f}")
            print(f"  Ratio (File1/File2): {total_costh1/total_costh2:.6f}")
            if total_costh2 > 0:
                print(f"  Relative difference: {((total_costh1-total_costh2)/total_costh2)*100:.2f}%")
        
        f1.Close()
        f2.Close()
        
        # Create visualization plots
        create_overlay_comparison_plots(root_file1, root_file2, eff_suffix1, eff_suffix2,
                                         label1, label2)
        create_ratio_analysis_plots(root_file1, root_file2, eff_suffix1, eff_suffix2,
                                     label1, label2)
        create_sensitivity_loss_comparison_plots(root_file1, root_file2, label1, label2)
        
        print("\n" + "="*70)
        print("TWO-FILE COMPARISON COMPLETE")
        print("Generated output files:")
        print(f"  - acceptance_overlay_comparison_{label1}_vs_{label2}.pdf")
        print(f"  - acceptance_ratio_analysis_{label1}_vs_{label2}.pdf")
        print(f"  - acceptance_A4_sensitivity_loss_comparison_{label1}_vs_{label2}.pdf "
              f"(if A4_SensitivityLossFactor present)")
        print("="*70 + "\n")
        
    except Exception as e:
        print(f"ERROR in compare_two_files: {e}")
        import traceback
        traceback.print_exc()

def create_comparison_plots(root_file, eff_suffix):
    """Create before/after comparison plots.
    
    Args:
        root_file (str): Path to ROOT file
        eff_suffix (str): Efficiency histogram suffix (_CC, _EtaOnly, or _CCAsym)
    """
    try:
        f = ROOT.TFile.Open(root_file, "READ")
        if not f or f.IsZombie():
            print(f"ERROR: Unable to open file {root_file}")
            return
        
        # Create canvas for comparison plots
        canvas = ROOT.TCanvas("c_comparison", "Before/After Comparison", 1400, 1000)
        canvas.Divide(3, 2)
        
        # Define histogram pairs to compare (using dynamic suffix)
        comparisons = [
            (f"eff_costheta_before{eff_suffix}", f"eff_costheta_after{eff_suffix}", "cos#theta_{CS}", 1),
            (f"eff_leadingPt_before{eff_suffix}", f"eff_leadingPt_after{eff_suffix}", "p_{T}(leading l) [GeV]", 2),
            (f"eff_subleadingPt_before{eff_suffix}", f"eff_subleadingPt_after{eff_suffix}", "p_{T}(subleading l) [GeV]", 3),
            (f"eff_deltaEta_before{eff_suffix}", f"eff_deltaEta_after{eff_suffix}", "|#Delta#eta(ll)|", 4),
            (f"eff_pT_Z_before{eff_suffix}", f"eff_pT_Z_after{eff_suffix}", "p_{T}(Z) [GeV]", 5),
            (f"eff_Y_ll_before{eff_suffix}", f"eff_Y_ll_after{eff_suffix}", "|y(Z)|", 6),
        ]
        
        print("\n" + "="*70)
        print("CREATING BEFORE/AFTER COMPARISON PLOTS")
        print("="*70)
        
        for h_before_name, h_after_name, var_label, pad_num in comparisons:
            h_before = f.Get(h_before_name)
            h_after = f.Get(h_after_name)
            
            if not h_before or not h_after:
                print(f"WARNING: Could not find {h_before_name} or {h_after_name}")
                continue
            
            # Normalize for comparison
            h_before_norm = h_before.Clone(f"{h_before_name}_norm")
            h_after_norm = h_after.Clone(f"{h_after_name}_norm")
            normalize_histogram(h_before_norm)
            normalize_histogram(h_after_norm)
            
            canvas.cd(pad_num)
            ROOT.gPad.SetLogy(0)
            
            # Draw histograms
            setup_histogram_style(h_before_norm, ROOT.kBlue + 1, 20)
            setup_histogram_style(h_after_norm, ROOT.kRed + 1, 22)
            
            h_before_norm.Draw("PE")
            h_after_norm.Draw("PE SAME")
            
            # Add legend
            legend = ROOT.TLegend(0.65, 0.75, 0.95, 0.95)
            legend.AddEntry(h_before_norm, "Before fiducial cut", "PE")
            legend.AddEntry(h_after_norm, "After fiducial cut", "PE")
            legend.Draw()
            
            # Add title
            h_before_norm.SetTitle(f"Normalized {var_label}")
            h_before_norm.GetXaxis().SetTitle(var_label)
            h_before_norm.GetYaxis().SetTitle("Normalized entries")
            
            print(f"Created comparison plot for {var_label}")
        
        canvas.SaveAs("acceptance_summary.pdf")
        print(f"\nSaved comparison plots to: acceptance_summary.pdf\n")
        f.Close()
        
    except Exception as e:
        print(f"ERROR in create_comparison_plots: {e}")
        import traceback
        traceback.print_exc()

def create_efficiency_plots(root_file, eff_suffix):
    """Create efficiency vs kinematic variable plots.
    
    Args:
        root_file (str): Path to ROOT file
        eff_suffix (str): Efficiency histogram suffix (_CC, _EtaOnly, or _CCAsym)
    """
    try:
        f = ROOT.TFile.Open(root_file, "READ")
        if not f or f.IsZombie():
            print(f"ERROR: Unable to open file {root_file}")
            return
        
        # Create canvas for efficiency plots
        canvas = ROOT.TCanvas("c_efficiency", "Efficiency Analysis", 1400, 900)
        canvas.Divide(3, 2)
        
        # Define efficiency pairs to calculate (using dynamic suffix)
        efficiencies = [
            (f"eff_costheta_before{eff_suffix}", f"eff_costheta_after{eff_suffix}", "cos#theta_{CS}", 1),
            (f"eff_leadingPt_before{eff_suffix}", f"eff_leadingPt_after{eff_suffix}", "p_{T}(leading l) [GeV]", 2),
            (f"eff_subleadingPt_before{eff_suffix}", f"eff_subleadingPt_after{eff_suffix}", "p_{T}(subleading l) [GeV]", 3),
            (f"eff_deltaEta_before{eff_suffix}", f"eff_deltaEta_after{eff_suffix}", "|#Delta#eta(ll)|", 4),
            (f"eff_pT_Z_before{eff_suffix}", f"eff_pT_Z_after{eff_suffix}", "p_{T}(Z) [GeV]", 5),
            (f"eff_Y_ll_before{eff_suffix}", f"eff_Y_ll_after{eff_suffix}", "|y(Z)|", 6),
        ]
        
        print("\n" + "="*70)
        print("CALCULATING EFFICIENCY (After/Before)")
        print("="*70)
        
        for h_before_name, h_after_name, var_label, pad_num in efficiencies:
            h_before = f.Get(h_before_name)
            h_after = f.Get(h_after_name)
            
            if not h_before or not h_after:
                print(f"WARNING: Could not find {h_before_name} or {h_after_name}")
                continue
            
            # Calculate efficiency
            h_eff = calculate_efficiency_histogram(h_after, h_before)
            
            canvas.cd(pad_num)
            ROOT.gPad.SetGrid(1, 1)
            
            # Setup and draw
            setup_histogram_style(h_eff, ROOT.kGreen + 2, 20)
            h_eff.SetTitle(f"Efficiency vs {var_label}")
            h_eff.GetXaxis().SetTitle(var_label)
            h_eff.GetYaxis().SetTitle("Efficiency")
            h_eff.GetYaxis().SetRangeUser(0.0, 1.1)
            h_eff.Draw("PE")
            
            # Add horizontal line at 1.0
            line = ROOT.TLine(h_eff.GetXaxis().GetXmin(), 1.0, 
                            h_eff.GetXaxis().GetXmax(), 1.0)
            line.SetLineStyle(2)
            line.SetLineColor(ROOT.kBlack)
            line.Draw()
            
            # Calculate average efficiency and print statistics
            integral_after = h_after.Integral()
            integral_before = h_before.Integral()
            avg_efficiency = integral_after / integral_before if integral_before > 0 else 0
            acceptance_loss = (1.0 - avg_efficiency) * 100.0
            
            print(f"\n{var_label}:")
            print(f"  Events before: {integral_before:.2f}")
            print(f"  Events after:  {integral_after:.2f}")
            print(f"  Average efficiency: {avg_efficiency:.4f}")
            print(f"  Acceptance loss: {acceptance_loss:.2f}%")
        
        canvas.SaveAs("acceptance_efficiency.pdf")
        print(f"\nSaved efficiency plots to: acceptance_efficiency.pdf\n")
        f.Close()
        
    except Exception as e:
        print(f"ERROR in create_efficiency_plots: {e}")
        import traceback
        traceback.print_exc()

def create_2d_analysis_plots(root_file, eff_suffix):
    """Create 2D kinematic analysis plots.
    
    Args:
        root_file (str): Path to ROOT file
        eff_suffix (str): Efficiency histogram suffix (_CC, _EtaOnly, or _CCAsym)
    """
    try:
        f = ROOT.TFile.Open(root_file, "READ")
        if not f or f.IsZombie():
            print(f"ERROR: Unable to open file {root_file}")
            return
        
        # Create canvas for 2D analysis with 6 plots (3x2 grid)
        canvas = ROOT.TCanvas("c_2d_analysis", "2D Kinematic Analysis", 1400, 1500)
        canvas.Divide(2, 3)
        
        print("\n" + "="*70)
        print("2D KINEMATIC ANALYSIS - BEFORE/AFTER FIDUCIAL CUTS")
        print("="*70)
        
        # Plot 1: pT(leading) vs pT(subleading) before cut
        canvas.cd(1)
        h_2d_pt_before = f.Get(f"eff_leadPtVsSubleadPt_before{eff_suffix}")
        if h_2d_pt_before:
            h_2d_pt_before.SetTitle("Before Cut: p_{T}(leading) vs p_{T}(subleading)")
            h_2d_pt_before.Draw("COLZ")
            print("✓ Plotted pT(leading) vs pT(subleading) BEFORE cut")
        else:
            print("WARNING: Could not find pT 2D histogram BEFORE cut")
        
        # Plot 2: pT(leading) vs pT(subleading) after cut
        canvas.cd(2)
        h_2d_pt_after = f.Get(f"eff_leadPtVsSubleadPt_after{eff_suffix}")
        if h_2d_pt_after:
            h_2d_pt_after.SetTitle("After Cut: p_{T}(leading) vs p_{T}(subleading)")
            h_2d_pt_after.Draw("COLZ")
            print("✓ Plotted pT(leading) vs pT(subleading) AFTER cut")
        else:
            print("WARNING: Could not find pT 2D histogram AFTER cut")
        
        # Plot 3: |eta(leading)| vs |eta(subleading)| before cut
        canvas.cd(3)
        h_2d_eta_before = f.Get(f"eff_etaLeadVsSubleadAbs_before{eff_suffix}")
        if h_2d_eta_before:
            h_2d_eta_before.SetTitle("Before Cut: |#eta(leading)| vs |#eta(subleading)|")
            h_2d_eta_before.Draw("COLZ")
            print("✓ Plotted |η(leading)| vs |η(subleading)| BEFORE cut")
        else:
            print("WARNING: Could not find eta 2D histogram BEFORE cut")
        
        # Plot 4: |eta(leading)| vs |eta(subleading)| after cut
        canvas.cd(4)
        h_2d_eta_after = f.Get(f"eff_etaLeadVsSubleadAbs_after{eff_suffix}")
        if h_2d_eta_after:
            h_2d_eta_after.SetTitle("After Cut: |#eta(leading)| vs |#eta(subleading)|")
            h_2d_eta_after.Draw("COLZ")
            print("✓ Plotted |η(leading)| vs |η(subleading)| AFTER cut")
        else:
            print("WARNING: Could not find eta 2D histogram AFTER cut")
        
        # Plot 5: cos(theta) vs |y(Z)| before cut
        canvas.cd(5)
        h_2d_costh_before = f.Get(f"eff_costhVsY_before{eff_suffix}")
        if h_2d_costh_before:
            h_2d_costh_before.SetTitle("Before Cut: cos#theta_{CS} vs |y(Z)|")
            h_2d_costh_before.Draw("COLZ")
            print("✓ Plotted cos(theta) vs |y(Z)| BEFORE cut")
        else:
            print("WARNING: Could not find cos(theta) vs Y 2D histogram BEFORE cut")
        
        # Plot 6: cos(theta) vs |y(Z)| after cut
        canvas.cd(6)
        h_2d_costh_after = f.Get(f"eff_costhVsY_after{eff_suffix}")
        if h_2d_costh_after:
            h_2d_costh_after.SetTitle("After Cut: cos#theta_{CS} vs |y(Z)|")
            h_2d_costh_after.Draw("COLZ")
            print("✓ Plotted cos(theta) vs |y(Z)| AFTER cut")
        else:
            print("WARNING: Could not find cos(theta) vs Y 2D histogram AFTER cut")
        
        canvas.SaveAs("acceptance_2d_analysis.pdf")
        print(f"\nSaved 2D analysis plots to: acceptance_2d_analysis.pdf\n")
        f.Close()
        
    except Exception as e:
        print(f"ERROR in create_2d_analysis_plots: {e}")
        import traceback
        traceback.print_exc()

def calculate_acceptance(root_file, eff_suffix):
    """
    Calculate acceptance based on the active fiducial cut.
    
    Args:
        root_file (str): Path to ROOT file output from AIZ.C
        eff_suffix (str): Efficiency histogram suffix (_CC, _EtaOnly, or _CCAsym)
    """
    
    try:
        f = ROOT.TFile.Open(root_file, "READ")
        if not f or f.IsZombie():
            print(f"ERROR: Unable to open file {root_file}")
            return
        
        # Try to get the acceptance histograms
        hLeadPt = f.Get("acceptance_leadingPt")
        hSubleadPt = f.Get("acceptance_subleadingPt")
        hLeadVsSubleadPt = f.Get("acceptance_leadingPt_vs_subleadingPt")
        
        if not hLeadPt:
            print(f"ERROR: Cannot find 'acceptance_leadingPt' histogram in {root_file}")
            print("Make sure AIZ.C was run with FiducialCutCCAsym = true")
            return
        
        print("\n" + "="*70)
        print(f"ACCEPTANCE CALCULATION (Fiducial cut: {eff_suffix.replace('_', '')})")
        print("="*70)
        
        # Count events above different thresholds for the leading pT
        total_weighted = hLeadPt.Integral()
        above_25_leading = hLeadPt.Integral(hLeadPt.FindBin(25.0), -1)
        above_27_leading = hLeadPt.Integral(hLeadPt.FindBin(27.0), -1)
        
        print(f"\nLeading pT Distribution Statistics:")
        print(f"  Total weighted events:           {total_weighted:.2f}")
        print(f"  Events with p_T(lead) ≥ 25 GeV: {above_25_leading:.2f}")
        print(f"  Events with p_T(lead) ≥ 27 GeV: {above_27_leading:.2f}")
        
        # Basic acceptance calculation (assumes subleading is already > 25 GeV in the histogram)
        if above_25_leading > 0:
            acceptance = above_27_leading / above_25_leading
            acceptance_loss = (1.0 - acceptance) * 100.0
            
            print(f"\nSimple Acceptance (leading pT only):")
            print(f"  Acceptance ratio:   {acceptance:.6f}")
            print(f"  Acceptance loss:    {acceptance_loss:.2f}%")
        
        # More detailed analysis using 2D histogram if available
        if hLeadVsSubleadPt:
            print(f"\n2D Analysis (p_T(leading) vs p_T(subleading)):")
            
            # Count events in different regions
            total_2d = hLeadVsSubleadPt.Integral()
            
            # Region: both above original thresholds (25, 25)
            y_bin_25 = hLeadVsSubleadPt.GetYaxis().FindBin(25.0)
            x_bin_25 = hLeadVsSubleadPt.GetXaxis().FindBin(25.0)
            x_bin_27 = hLeadVsSubleadPt.GetXaxis().FindBin(27.0)
            
            events_25_25 = hLeadVsSubleadPt.Integral(x_bin_25, -1, y_bin_25, -1)
            events_27_25 = hLeadVsSubleadPt.Integral(x_bin_27, -1, y_bin_25, -1)
            
            print(f"  Events with p_T(lead)≥25 and p_T(sublead)≥25 GeV: {events_25_25:.2f}")
            print(f"  Events with p_T(lead)≥27 and p_T(sublead)≥25 GeV: {events_27_25:.2f}")
            
            if events_25_25 > 0:
                acceptance_2d = events_27_25 / events_25_25
                acceptance_loss_2d = (1.0 - acceptance_2d) * 100.0
                
                print(f"\n  Acceptance ratio:   {acceptance_2d:.6f}")
                print(f"  Acceptance loss:    {acceptance_loss_2d:.2f}%")
        
        # Analyze cos(theta) efficiency
        print(f"\n" + "="*70)
        print("COS(THETA) ACCEPTANCE ANALYSIS")
        print("="*70)
        
        h_costh_before = f.Get(f"eff_costheta_before{eff_suffix}")
        h_costh_after = f.Get(f"eff_costheta_after{eff_suffix}")
        
        if h_costh_before and h_costh_after:
            total_costh_before = h_costh_before.Integral()
            total_costh_after = h_costh_after.Integral()
            
            print(f"\nCos(theta) Statistics:")
            print(f"  Events before cut: {total_costh_before:.2f}")
            print(f"  Events after cut:  {total_costh_after:.2f}")
            
            if total_costh_before > 0:
                eff_costh = total_costh_after / total_costh_before
                loss_costh = (1.0 - eff_costh) * 100.0
                print(f"  Overall efficiency: {eff_costh:.4f}")
                print(f"  Acceptance loss: {loss_costh:.2f}%")
            
            # Bin-by-bin efficiency analysis
            print(f"\n  Bin-by-bin cos(theta) efficiency:")
            print(f"  {'cos(theta) range':<20} {'Before':<15} {'After':<15} {'Efficiency':<15}")
            print(f"  {'-'*65}")
            
            nbins = h_costh_before.GetNbinsX()
            for i in range(1, min(nbins + 1, 11)):  # Show first 10 bins
                bin_low = h_costh_before.GetBinLowEdge(i)
                bin_high = bin_low + h_costh_before.GetBinWidth(i)
                before_val = h_costh_before.GetBinContent(i)
                after_val = h_costh_after.GetBinContent(i)
                
                if before_val > 0:
                    eff = after_val / before_val
                    print(f"  [{bin_low:6.3f}, {bin_high:6.3f}]{' '*4} {before_val:12.2f}  {after_val:12.2f}  {eff:14.4f}")
        
        # Print differential pT analysis
        print(f"\n" + "="*70)
        print("DIFFERENTIAL PtTHRESHOLD ANALYSIS")
        print("="*70)
        print(f"\n  {'pT threshold (GeV)':<20} {'Leading pT ≥ threshold':<25} {'Efficiency':<15}")
        print(f"  {'-'*60}")
        
        thresholds = [20.0, 22.0, 24.0, 25.0, 26.0, 27.0, 28.0, 30.0]
        for threshold in thresholds:
            bin_idx = hLeadPt.FindBin(threshold)
            events = hLeadPt.Integral(bin_idx, -1)
            if above_25_leading > 0:
                eff = events / above_25_leading
                print(f"  {threshold:18.1f}  {events:20.2f}  {eff:14.4f}")
        
        print("\n" + "="*70)
        print("INTERPRETATION:")
        print("  - Acceptance loss represents % of events rejected by 27 GeV cut")
        print("  - Use this to quantify impact on statistical precision")
        print("  - Efficiency varies with kinematic variables due to event topology")
        print("="*70 + "\n")
        
        f.Close()
        
    except Exception as e:
        print(f"ERROR: {e}")
        import traceback
        traceback.print_exc()

MULTI_FILE_COLORS = [ROOT.kBlue + 1, ROOT.kRed + 1, ROOT.kGreen + 2, ROOT.kMagenta + 1,
                     ROOT.kOrange + 7, ROOT.kCyan + 2, ROOT.kViolet + 1, ROOT.kGray + 2]
MULTI_FILE_MARKERS = [20, 22, 21, 23, 33, 34, 29, 47]

def unique_labels(labels):
    """Make labels unique (e.g. two files with the same cut) by appending _2, _3, ..."""
    seen = {}
    result = []
    for label in labels:
        seen[label] = seen.get(label, 0) + 1
        result.append(label if seen[label] == 1 else f"{label}_{seen[label]}")
    return result

def multi_ratio_y_range(ratios, x_range=None):
    """Common y range for several ratio histograms, optionally restricted to an x range."""
    values = []
    for h_ratio in ratios:
        for b in range(1, h_ratio.GetNbinsX() + 1):
            x = h_ratio.GetXaxis().GetBinCenter(b)
            v = h_ratio.GetBinContent(b)
            if x_range and not (x_range[0] <= x <= x_range[1]):
                continue
            if v != 0 and math.isfinite(v):
                values.append(v)
    if not values:
        return None
    low, high = min(1.0, min(values)), max(1.0, max(values))
    padding = max((high - low) * 0.1, 0.02)
    return low - padding, high + padding

def create_multi_overlay_comparison_plots(root_files, suffixes, labels, normalized):
    """Overlay N files per variable; ratio panels show each file divided by the first.

    Args:
        root_files (list[str]): ROOT files; the first one is the reference
        suffixes (list[str]): Efficiency histogram suffix of each file
        labels (list[str]): Unique short label of each file
        normalized (bool): Compare unit-area histograms if True, original histograms otherwise
    """
    files = [ROOT.TFile.Open(f, "READ") for f in root_files]
    if any((not f) or f.IsZombie() for f in files):
        print("ERROR: Unable to open one or more files")
        return

    variables = [
        ("eff_costheta_after", "cos#theta_{CS}"),
        ("eff_leadingPt_after", "p_{T}(leading l) [GeV]"),
        ("eff_subleadingPt_after", "p_{T}(subleading l) [GeV]"),
        ("eff_deltaEta_after", "|#Delta#eta(ll)|"),
        ("eff_pT_Z_after", "p_{T}(Z) [GeV]"),
        ("eff_Y_ll_after", "|y(Z)|"),
    ]
    zoom_x_ranges = {
        "|#Delta#eta(ll)|": (0.0, 2.2),
    }
    # Ranges used to choose the y zoom; subleading pT keeps its full x axis
    y_focus_ranges = {
        "p_{T}(subleading l) [GeV]": (25.0, 60.0),
        "|#Delta#eta(ll)|": (0.0, 2.2),
    }
    kind = "Normalized" if normalized else "Unnormalized"
    ref = labels[0]

    canvas = ROOT.TCanvas(f"c_multi_{kind}", f"{kind} multi-file comparison", 1600, 1680)
    canvas.Divide(2, 6)
    keep_alive = []

    for row, (base_name, var_label) in enumerate(variables):
        hists = []
        for f, suffix in zip(files, suffixes):
            h = f.Get(f"{base_name}{suffix}")
            if not h:
                print(f"WARNING: Could not find {base_name}{suffix} in {f.GetName()}")
                break
            hists.append(h.Clone(f"{base_name}{suffix}_{len(keep_alive)}"))
        if len(hists) != len(files):
            continue
        if normalized:
            for h in hists:
                normalize_histogram(h)

        canvas.cd(2 * row + 1)
        ROOT.gPad.SetLogy(0)
        for i, h in enumerate(hists):
            setup_histogram_style(h, MULTI_FILE_COLORS[i % len(MULTI_FILE_COLORS)],
                                  MULTI_FILE_MARKERS[i % len(MULTI_FILE_MARKERS)])
        hists[0].SetTitle(f"{kind} {var_label} - Overlay")
        hists[0].GetXaxis().SetTitle(var_label)
        hists[0].GetYaxis().SetTitle("Normalized entries" if normalized else "Entries")
        hists[0].SetMaximum(1.2 * max(h.GetMaximum() for h in hists))
        hists[0].Draw("PE")
        for h in hists[1:]:
            h.Draw("PE SAME")
        legend = ROOT.TLegend(0.60, 0.88 - 0.06 * len(hists), 0.92, 0.88)
        for h, label in zip(hists, labels):
            legend.AddEntry(h, label, "PE")
        legend.Draw()

        canvas.cd(2 * row + 2)
        ROOT.gPad.SetGrid(1, 1)
        ratios = []
        for i in range(1, len(hists)):
            h_ratio = calculate_ratio_histogram(hists[i], hists[0])
            h_ratio.SetName(f"ratio_{base_name}_{i}_{len(keep_alive)}")
            setup_histogram_style(h_ratio, MULTI_FILE_COLORS[i % len(MULTI_FILE_COLORS)],
                                  MULTI_FILE_MARKERS[i % len(MULTI_FILE_MARKERS)])
            ratios.append(h_ratio)

        x_range = zoom_x_ranges.get(var_label)
        y_range = None
        y_focus = y_focus_ranges.get(var_label)
        if y_focus:
            y_range = multi_ratio_y_range(ratios, y_focus)
        else:
            lows, highs = [], []
            for h_ratio, h_den in zip(ratios, [hists[0]] * len(ratios)):
                set_ratio_axis_range(h_ratio, h_den)
                if h_ratio.GetMinimum() != -1111:
                    lows.append(h_ratio.GetMinimum())
                    highs.append(h_ratio.GetMaximum())
            if lows:
                y_range = (min(lows), max(highs))

        zoom_suffix = " (zoomed)" if y_focus else ""
        ratios[0].SetTitle(f"{kind} ratio (file/{ref}) - {var_label}{zoom_suffix}")
        ratios[0].GetXaxis().SetTitle(var_label)
        ratios[0].GetYaxis().SetTitle(f"{kind} ratio to {ref}")
        for h_ratio in ratios:
            if x_range:
                h_ratio.GetXaxis().SetRangeUser(*x_range)
            if y_range:
                h_ratio.SetMinimum(y_range[0])
                h_ratio.SetMaximum(y_range[1])
        ratios[0].Draw("PE")
        for h_ratio in ratios[1:]:
            h_ratio.Draw("PE SAME")
        line_x_min, line_x_max = x_range if x_range else (
            ratios[0].GetXaxis().GetXmin(), ratios[0].GetXaxis().GetXmax())
        line = ROOT.TLine(line_x_min, 1.0, line_x_max, 1.0)
        line.SetLineStyle(2)
        line.SetLineColor(ROOT.kBlack)
        line.Draw()

        keep_alive.extend([hists, ratios, legend, line])
        print(f"Created {kind.lower()} multi-file plot for {var_label}")

    tag = "_".join(labels)
    output_name = (f"acceptance_overlay_comparison_multi_{tag}.pdf" if normalized
                   else f"acceptance_overlay_comparison_unnormalized_multi_{tag}.pdf")
    canvas.SaveAs(output_name)
    print(f"Saved {kind.lower()} multi-file overlay comparison to: {output_name}\n")
    for f in files:
        f.Close()

def create_multi_sensitivity_loss_comparison_plots(root_files, labels):
    """Compare A4_SensitivityLossFactor across N files; ratio panel is file/first file."""
    files = [ROOT.TFile.Open(f, "READ") for f in root_files]
    if any((not f) or f.IsZombie() for f in files):
        print("ERROR: Unable to open one or more files")
        return
    hists = [f.Get("A4_SensitivityLossFactor") for f in files]
    if any(not h for h in hists):
        print("WARNING: A4_SensitivityLossFactor not found in one or more files; "
              "skipping sensitivity-loss comparison")
        for f in files:
            f.Close()
        return

    print("\n" + "="*70)
    print("A4 SENSITIVITY LOSS FACTOR COMPARISON (MULTI-FILE)")
    print("="*70)

    ref = labels[0]
    canvas = ROOT.TCanvas("c_A4_sensitivity_loss_multi",
                          "A4 Sensitivity Loss Factor: Multi-file comparison", 1600, 700)
    canvas.Divide(2, 1)

    # No Sumw2 is stored for this histogram, so drop the sqrt(content) pseudo-errors
    clones = [h.Clone(f"A4_loss_multi_{i}") for i, h in enumerate(hists)]
    for i, h in enumerate(clones):
        for b in range(1, h.GetNbinsX() + 1):
            h.SetBinError(b, 0.0)
        setup_histogram_style(h, MULTI_FILE_COLORS[i % len(MULTI_FILE_COLORS)],
                              MULTI_FILE_MARKERS[i % len(MULTI_FILE_MARKERS)])

    canvas.cd(1)
    ROOT.gPad.SetGrid(1, 1)
    ROOT.gPad.SetLogy(1)
    clones[0].SetTitle("A_{4} Sensitivity Loss Factor - Overlay")
    clones[0].GetYaxis().SetTitle("#sigma(A_{4})_{after}/#sigma(A_{4})_{before}")
    clones[0].SetMinimum(0.5)
    clones[0].Draw("P")
    for h in clones[1:]:
        h.Draw("P SAME")
    legend = ROOT.TLegend(0.60, 0.88 - 0.06 * len(clones), 0.92, 0.88)
    for h, label in zip(clones, labels):
        legend.AddEntry(h, label, "P")
    legend.Draw()
    unity = ROOT.TLine(clones[0].GetXaxis().GetXmin(), 1.0, clones[0].GetXaxis().GetXmax(), 1.0)
    unity.SetLineStyle(2)
    unity.Draw()

    canvas.cd(2)
    ROOT.gPad.SetGrid(1, 1)
    ratios = []
    for i in range(1, len(hists)):
        h_ratio = clones[i].Clone(f"A4_loss_multi_ratio_{i}")
        h_ratio.Reset()
        for b in range(1, hists[0].GetNbinsX() + 1):
            v0, vi = hists[0].GetBinContent(b), hists[i].GetBinContent(b)
            if v0 != 0 and vi != 0:
                h_ratio.SetBinContent(b, vi / v0)
                h_ratio.SetBinError(b, 0.0)
        h_ratio.SetLineColor(clones[i].GetLineColor())
        h_ratio.SetMarkerColor(clones[i].GetMarkerColor())
        h_ratio.SetMarkerStyle(clones[i].GetMarkerStyle())
        ratios.append(h_ratio)
    y_range = multi_ratio_y_range(ratios)
    ratios[0].SetTitle(f"Loss factor ratio (file/{ref}) - A_{{4}} Sensitivity Loss Factor")
    ratios[0].GetYaxis().SetTitle(f"Loss factor ratio to {ref}")
    for h_ratio in ratios:
        if y_range:
            h_ratio.SetMinimum(y_range[0])
            h_ratio.SetMaximum(y_range[1])
    ratios[0].Draw("P")
    for h_ratio in ratios[1:]:
        h_ratio.Draw("P SAME")
    ratio_unity = ROOT.TLine(ratios[0].GetXaxis().GetXmin(), 1.0, ratios[0].GetXaxis().GetXmax(), 1.0)
    ratio_unity.SetLineStyle(2)
    ratio_unity.Draw()

    output_name = f"acceptance_A4_sensitivity_loss_comparison_multi_{'_'.join(labels)}.pdf"
    canvas.SaveAs(output_name)
    print(f"\nSaved multi-file A4 sensitivity-loss comparison to: {output_name}")

    header = f"{'BinLow':>8} {'BinHigh':>8}" + "".join(f" {l:>12}" for l in labels)
    print("\n" + header)
    for b in range(1, hists[0].GetNbinsX() + 1):
        values = [h.GetBinContent(b) for h in hists]
        if any(v != 0 for v in values):
            print(f"{hists[0].GetXaxis().GetBinLowEdge(b):8.2f} {hists[0].GetXaxis().GetBinUpEdge(b):8.2f}"
                  + "".join(f" {v:12.4f}" for v in values))
    for f in files:
        f.Close()

def get_total_acceptance(root_file, eff_suffix):
    """Return (before, after, acceptance) from the cos(theta) before/after-cut histograms."""
    f = ROOT.TFile.Open(root_file, "READ")
    if not f or f.IsZombie():
        return None
    h_before = f.Get(f"eff_costheta_before{eff_suffix}")
    h_after = f.Get(f"eff_costheta_after{eff_suffix}")
    if not h_before or not h_after:
        f.Close()
        return None
    before, after = h_before.Integral(), h_after.Integral()
    f.Close()
    return before, after, (after / before if before > 0 else None)

def print_total_acceptance_table(root_files, suffixes, labels):
    """Print total acceptance per file and relative to the first (reference) file."""
    results = [get_total_acceptance(f, s) for f, s in zip(root_files, suffixes)]
    ref = results[0][2] if results[0] else None
    print("\n" + "="*70)
    print("TOTAL ACCEPTANCE TABLE (after cut / before cut)")
    print("="*70)
    print(f"{'File':<28}{'Before':>12}{'After':>12}{'Acceptance':>12}{'Rel. to ref':>12}")
    print("-"*76)
    for label, r in zip(labels, results):
        if not r or r[2] is None:
            print(f"{label:<28}{'n/a':>12}{'n/a':>12}{'n/a':>12}{'n/a':>12}")
            continue
        rel = f"{r[2]/ref:.4f}" if ref else "n/a"
        print(f"{label:<28}{r[0]:>12.2f}{r[1]:>12.2f}{r[2]:>12.5f}{rel:>12}")
    print("="*70)

def compare_multiple_files(root_files):
    """Compare three or more ROOT files; the first file is the reference for all ratios."""
    suffixes = [detect_efficiency_suffix(f) for f in root_files]
    if not all(suffixes):
        print("ERROR: Could not detect efficiency histograms in one or more files")
        return
    labels = unique_labels([derive_cut_label(f) for f in root_files])

    print("\n" + "="*70)
    print(f"MULTI-FILE COMPARISON MODE ({len(root_files)} files, reference = {labels[0]})")
    print("="*70)
    for i, (f, suffix, label) in enumerate(zip(root_files, suffixes, labels), start=1):
        print(f"File {i}: {f}")
        print(f"  Detected cut mode (histogram suffix): {get_suffix_label(suffix)}")
        print(f"  Cut-mode label: {label}")
    print("="*70)

    print_total_acceptance_table(root_files, suffixes, labels)

    create_multi_overlay_comparison_plots(root_files, suffixes, labels, normalized=True)
    create_multi_overlay_comparison_plots(root_files, suffixes, labels, normalized=False)
    create_multi_sensitivity_loss_comparison_plots(root_files, labels)

    tag = "_".join(labels)
    print("\n" + "="*70)
    print("MULTI-FILE COMPARISON COMPLETE")
    print("Generated output files:")
    print(f"  - acceptance_overlay_comparison_multi_{tag}.pdf")
    print(f"  - acceptance_overlay_comparison_unnormalized_multi_{tag}.pdf")
    print(f"  - acceptance_A4_sensitivity_loss_comparison_multi_{tag}.pdf "
          f"(if A4_SensitivityLossFactor present)")
    print("="*70 + "\n")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage (Single file mode):")
        print("  python calculate_acceptance.py <output_file.root>")
        print("\nUsage (Two-file comparison mode):")
        print("  python calculate_acceptance.py <file_with_cut.root> <file_without_cut.root>")
        print("\nUsage (Multi-file comparison mode, 3 or more files; first file is the reference):")
        print("  python calculate_acceptance.py <ref.root> <file2.root> <file3.root> [...]")
        print("\nExample (single file):")
        print("  python calculate_acceptance.py AI_Z_Truth_Fiducial_CCAsym_Zai_finalbinning_pT_NormXsec.root")
        print("\nExample (two-file comparison):")
        print("  python calculate_acceptance.py AI_Z_Truth_Fiducial_CCAsym_testPowheg_Y_NormXsec.root AI_Z_Truth_Fiducial_testPowheg_Y_NormXsec.root")
        print("\nSingle file mode analyzes a single ROOT file with before/after fiducial cut distributions.")
        print("Two-file comparison mode compares acceptance between two files with ratio analysis.")
        sys.exit(1)
    
    if len(sys.argv) == 2:
        # Single file mode
        root_file = sys.argv[1]
        
        # Detect which efficiency histogram suffix is present
        eff_suffix = detect_efficiency_suffix(root_file)
        if not eff_suffix:
            print(f"ERROR: Could not find efficiency histograms in {root_file}")
            print("Make sure AIZ.C was run with one of: FiducialCut, FiducialCutEtaonly, or FiducialCutCCAsym enabled")
            sys.exit(1)
        
        print(f"\nDetected fiducial cut mode: {get_suffix_label(eff_suffix)}")
        print(f"Using histogram suffix: {eff_suffix}\n")
        
        # Run all analyses
        calculate_acceptance(root_file, eff_suffix)
        create_comparison_plots(root_file, eff_suffix)
        create_efficiency_plots(root_file, eff_suffix)
        create_2d_analysis_plots(root_file, eff_suffix)
        
        print("\n" + "="*70)
        print("ANALYSIS COMPLETE")
        print("Generated output files:")
        print("  - acceptance_summary.pdf")
        print("  - acceptance_efficiency.pdf")
        print("  - acceptance_2d_analysis.pdf")
        print("="*70 + "\n")
    
    elif len(sys.argv) == 3:
        # Two-file comparison mode
        root_file1 = sys.argv[1]
        root_file2 = sys.argv[2]
        
        compare_two_files(root_file1, root_file2)
    
    else:
        # Multi-file comparison mode (3 or more files, first is the reference)
        compare_multiple_files(sys.argv[1:])
